<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
    <a href="<?php echo $block->getBaseUrl(); ?>blog/index/create" class="action primary">Create New Post</a>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>URL Key</th>
        <th>Content</th>
        <th>Status</th>
        <th colspan="2">Action</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $posts = $block->getPosts();

    foreach ($posts as $post) :
        ?>
        <tr style="text-align: left; padding: 8px;">
            <td><?php echo $post->getId(); ?></td>
            <td><?php echo $post->getName(); ?></td>
            <td><?php echo $post->getUrlKey(); ?></td>
            <td><?php echo $post->getContent(); ?></td>
            <td><?php $status = $post->getStatus();
                if ($status == 1) {
                    echo "Public";
                } else {
                    echo "Draft";
                }
                ?></td>
            <td>
                <a href="<?php echo $block->getBaseUrl(); ?>blog/index/edit/post_id/<?php echo $post->getId(); ?>"
                   class="action primary">Edit</a>
                <a style="color: #fff; background-color: red;"
                   href="<?php echo $block->getBaseUrl(); ?>blog/index/delete/post_id/<?php echo $post->getId(); ?>"
                   class="action primary">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
